export const DOM = {
  formGasto: document.getElementById('form-gasto'),
  descGasto: document.getElementById('desc-gasto'),
  valorGasto: document.getElementById('valor-gasto'),
  catGasto: document.getElementById('cat-gasto'),
  tipoGasto: document.getElementById('tipo-gasto'),
  parcelasGasto: document.getElementById('parcelas-gasto'),
  dataGasto: document.getElementById('data-gasto'),

  formGanho: document.getElementById('form-ganho'),
  descGanho: document.getElementById('desc-ganho'),
  valorGanho: document.getElementById('valor-ganho'),
  catGanho: document.getElementById('cat-ganho'),
  tipoGanho: document.getElementById('tipo-ganho'),
  dataGanho: document.getElementById('data-ganho'),

  inputSalario: document.getElementById('input-salario'),

  cardResumo: document.getElementById('card-resumo'),
  resRenda: document.getElementById('res-renda'),
  resGastos: document.getElementById('res-gastos'),
  resSaldo: document.getElementById('res-saldo'),
  resSaldoLivre: document.getElementById('res-saldo-livre'),
  resumoItemLivre: document.getElementById('resumo-item-livre'),
  resumoDivisorLivre: document.getElementById('resumo-divisor-livre'),

  listaTransacoes: document.getElementById('lista-transacoes'),
  listaGanhos: document.getElementById('lista-ganhos'),

  cardNavegarMes: document.getElementById('card-navegar-mes'),
  seletorMes: document.getElementById('seletor-mes'),
  avisoMesFechado: document.getElementById('aviso-mes-fechado'),
  badgeMesGastos: document.getElementById('badge-mes-gastos'),
  badgeMesGanhos: document.getElementById('badge-mes-ganhos'),
  badgeMesGraficos: document.getElementById('badge-mes-graficos'),

  formLimite: document.getElementById('form-limite'),
  catLimite: document.getElementById('cat-limite'),
  valorLimite: document.getElementById('valor-limite'),
  listaLimites: document.getElementById('lista-limites'),

  formPoupanca: document.getElementById('form-poupanca'),
  tipoPoupanca: document.getElementById('tipo-poupanca'),
  valorPoupanca: document.getElementById('valor-poupanca'),
  descPoupanca: document.getElementById('desc-poupanca'),
  poupancaSaldo: document.getElementById('poupanca-saldo'),
  listaPoupanca: document.getElementById('lista-poupanca'),

  streakBadge: document.getElementById('streak-badge'),
  streakNumero: document.getElementById('streak-numero'),
  fraseEmocional: document.getElementById('frase-emocional'),

  btnFecharMes: document.getElementById('btn-fechar-mes'),

  btnTema: document.getElementById('btn-tema'),

  btnMenu: document.getElementById('btn-menu'),
  btnFecharMenu: document.getElementById('btn-fechar-menu'),
  btnComoUsar: document.getElementById('btn-como-usar'),

  onboardingOverlay: document.getElementById('onboarding-overlay'),
  btnOnboardingTour: document.getElementById('btn-onboarding-tour'),
  btnOnboardingPular: document.getElementById('btn-onboarding-pular'),

  tourOverlay: document.getElementById('tour-overlay'),
  tourEmoji: document.getElementById('tour-emoji'),
  tourTitulo: document.getElementById('tour-titulo'),
  tourTexto: document.getElementById('tour-texto'),
  tourProgresso: document.getElementById('tour-progresso'),
  btnTourVoltar: document.getElementById('btn-tour-voltar'),
  btnTourProximo: document.getElementById('btn-tour-proximo'),
  btnTourPular: document.getElementById('btn-tour-pular'),
  menuOverlay: document.getElementById('menu-overlay'),

  btnExportarBackup: document.getElementById('btn-exportar-backup'),
  btnImportarBackup: document.getElementById('btn-importar-backup'),
  inputImportarBackup: document.getElementById('input-importar-backup'),
  btnExportarCsv: document.getElementById('btn-exportar-csv'),
  backupStatus: document.getElementById('backup-status'),

  nuvemStatus: document.getElementById('nuvem-status'),
  nuvemDeslogado: document.getElementById('nuvem-deslogado'),
  nuvemLogado: document.getElementById('nuvem-logado'),
  nuvemEmailUsuario: document.getElementById('nuvem-email-usuario'),
  btnSairNuvem: document.getElementById('btn-sair-nuvem'),
  btnEnviarNuvem: document.getElementById('btn-enviar-nuvem'),
  btnBaixarNuvem: document.getElementById('btn-baixar-nuvem'),
  formLogin: document.getElementById('form-login'),
  loginEmail: document.getElementById('login-email'),
  loginSenha: document.getElementById('login-senha'),
  btnCadastrar: document.getElementById('btn-cadastrar'),
  loginStatus: document.getElementById('login-status'),

  carrosselSlides: document.querySelectorAll('.carrossel-slide'),
  carrosselPrev: document.getElementById('carrossel-prev'),
  carrosselNext: document.getElementById('carrossel-next'),
  carrosselDots: document.getElementById('carrossel-dots'),
  carrosselTitulo: document.getElementById('carrossel-titulo'),
  carrosselVariacao: document.getElementById('carrossel-variacao'),

  canvasPizza: document.getElementById('pieChart'),
  canvasLinha: document.getElementById('lineChart'),
  canvasGuardado: document.getElementById('guardadoChart'),
  canvasDetalhe: document.getElementById('detalheChart'),
  legendaPizza: document.getElementById('legenda-pizza'),

  modalOverlay: document.getElementById('modal-overlay'),
  modalTitulo: document.getElementById('modal-titulo'),
  modalTotal: document.getElementById('modal-total'),
  modalPercentual: document.getElementById('modal-percentual'),
  modalFechar: document.getElementById('modal-fechar'),
  modalListaItens: document.getElementById('modal-lista-itens'),
  modalLimiteWrap: document.getElementById('modal-limite-wrap'),
  modalLimiteTexto: document.getElementById('modal-limite-texto'),
  modalLimitePercentual: document.getElementById('modal-limite-percentual'),
  modalLimiteBarra: document.getElementById('modal-limite-barra'),
  modalLimiteAviso: document.getElementById('modal-limite-aviso'),
};
